services:
    psql:
        container_name: psql
        image: postgres:17
        ports:
            - "5432:5432"
        volumes:
            - psql_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: ${PSQL_USER}
            POSTGRES_PASSWORD: ${PSQL_PASSWORD}
        networks:
            - app-network
        restart: unless-stopped

    kc-psql:
        container_name: kc-psql
        image: postgres:17
        volumes:
            - kc-psql_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: ${KC_PSQL_USER}
            POSTGRES_PASSWORD: ${KC_PSQL_PASSWORD}
        ports:
            - "5433:5432"
        networks:
            - app-network
        restart: unless-stopped

    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:latest
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://kc-psql:5432/keycloak
            KC_DB_USERNAME: ${KC_PSQL_USER}
            KC_DB_PASSWORD: ${KC_PSQL_PASSWORD}

            KC_HOSTNAME: localhost
            KC_HOSTNAME_PORT: 8080
            KC_HOSTNAME_STRICT: false
            KC_HOSTNAME_STRICT_HTTPS: false

            KC_LOG_LEVEL: info
            KC_METRICS_ENABLED: true
            KC_HEALTH_ENABLED: true
            KC_BOOTSTRAP_ADMIN_USERNAME: admin
            KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        command: start-dev
        depends_on:
            - kc-psql
        ports:
            - "8080:8080"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    psql_data:
    kc-psql_data: